MvcUunStokProjesi/MvcUunStokProjesi/Controllers/urunlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;// bunlar eklnemeli sayfalama için 
using PagedList.Mvc; // buda 

using MvcUunStokProjesi.Models.Entity;


namespace MvcUunStokProjesi.Controllers
{
    public class urunlerController : Controller
    {
        // GET: urunler
        MvcUrunstokEntities2 db = new MvcUrunstokEntities2();
        public ActionResult Index(int sayfa=1)
        {
            // var degerler = db.tblurunler.ToList();
            var degerler = db.tblurunler.ToList().ToPagedList(sayfa, 4);
            return View(degerler);
        }

        [HttpGet] // bu sayfa geri döndüğünde olsun 
        public ActionResult urunekle()
        {
            List<SelectListItem> degerler = (from i in db.tblkotegoriler.ToList() // linq sorgusu ,kategorileri listele ve i ye ata ,sonra seçili liste öğelerinden yeni seç kategoriad texte id yi                                          
                                             select new SelectListItem      // value ata ve bunların hepsini listele 
                                             {
                                                 Text = i.kategoriad,
                                                 Value   = i.kategoriid.ToString()
                                             }).ToList();

            ViewBag.dgr = degerler; // buda diğer sayfada tanımlanması için yapılması lazım çok önemli bir şey  

            return View();
        }

        [HttpPost] // bu post olayı olduğunda olsun butona basıldığında olsun 
        public ActionResult urunekle (tblurunler p1)
        {
            var ktg = db.tblkotegoriler.Where(m => m.kategoriid == p1.tblkotegoriler.kategoriid).FirstOrDefault();
            // db kategoriler içinde şart ling sorugusundaki kategoriid eşitse p1 deki kategori id sinde ilk olanı getirsin 
            p1.tblkotegoriler = ktg;
            db.tblurunler.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index"); // kaydetme işlemi olduktan sonra index sayfasına yönlendirsin 


        }
        public ActionResult sil(int id) // burdaki sil view deki adres te sil nasıl yazılmışsa bunu öyle yaz
        {
            var urun = db.tblurunler.Find(id);
            db.tblurunler.Remove(urun);
            db.SaveChanges();// değişliklikleri kaydet 
            return RedirectToAction("Index");

        }

        public ActionResult urungetir(int id)
        {
            var urun = db.tblurunler.Find(id);

            List<SelectListItem> degerler = (from i in db.tblkotegoriler.ToList() // linq sorgusu ,kategorileri listele ve i ye ata ,sonra seçili liste öğelerinden yeni seç kategoriad texte id yi                                          
                                             select new SelectListItem      // value ata ve bunların hepsini listele 
                                             {
                                                 Text = i.kategoriad,
                                                 Value = i.kategoriid.ToString()
                                             }).ToList();

            ViewBag.dgr = degerler;
            return View("urungetir", urun);

        }

        public ActionResult guncelle(tblurunler p)
        {
            var urun = db.tblurunler.Find(p.urunid);
            urun.urunad = p.urunad;
            urun.marka = p.marka;
            urun.fiyat = p.fiyat;
            urun.stok = p.stok;
            //  urun.urunkategori = p.urunkategori;// büyle yaparsan hata alırsın diğerleri değişir bu değişmez ve hata alırsın 
      //    var ktg = db.tblkotegoriler.Where(m => m.kategoriid == p.tblkotegoriler.kategoriid).FirstOrDefault();
        //   urun.urunkategori = ktg.kategoriid;
            db.SaveChanges();
            return RedirectToAction("Index");

        }


    }
}

MvcUunStokProjesi/MvcUunStokProjesi/Views/urunler/Index.cshtml
@using MvcUunStokProjesi.Models.Entity;
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<tblurunler>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th> Ürün Id </th>
            <th> Ürün Adı </th>
            <th>Markası</th>
            <th>Kategori</th>
            <th>Fiyat</th>
            <th>Stok</th>
            <th>Sil</th>
            <th>Güncelle</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var urn in Model)
        {
            <tr>
                <th>@urn.urunid</th>
                <td>@urn.urunad</td>
                <td>@urn.marka</td>
                <td>@urn.tblkotegoriler.kategoriad</td>
                <td>@urn.fiyat</td>
                <td>@urn.stok</td>
                <td> <a href="/urunler/sil/@urn.urunid " class="btn btn-danger">SİL </a></td>
                <td> <a href="/urunler/urungetir/@urn.urunid" class="btn btn-success">GÜNCELLE </a></td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))

<a href="/urunler/urunekle/" class="btn btn-primary"> YENİ ÜRÜN EKLE</a> <!--bu view den adrese bak karıştırırsan -->
@*

    <link href="~/Content/DataTables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script> *@
@*   <script>
        $('#tbl1').dataTable({});
    </script>     *@


<!--datatables türkçeleştirilmiş hali -->
@*
    <script>
        $('#tbl1').DataTable({
            language: {
                info: "_TOTAL_ kayıttan _START_ - _END_ kayıt gösteriliyor.",
                infoEmpty: "Gösterilecek hiç kayıt yok.",
                loadingRecords: "Kayıtlar yükleniyor.",
                lengthMenu: "Sayfada _MENU_ kayıt göster",
                zeroRecords: "Tablo boş",
                search: "Arama:",
                infoFiltered: "(toplam _MAX_ kayıttan filtrelenenler)",
                buttons: {
                    copyTitle: "Panoya kopyalandı.",
                    copySuccess: "Panoya %d satır kopyalandı",
                    copy: "Kopyala",
                    print: "Yazdır",
                },

                paginate: {
                    first: "İlk",
                    previous: "Önceki",
                    next: "Sonraki",
                    last: "Son"
                },
            }
        });
    </script>
*@

MvcUunStokProjesi/MvcUunStokProjesi/Views/urunler/urunekle.cshtml
@model MvcUunStokProjesi.Models.Entity.tblurunler
@{
    ViewBag.Title = "urunekle";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<form method="post" class="form-group">

    <div>

        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="urunad"  required=""  maxlength="30" placeholder="Ürün Adını Yazın"/>

    </div>
    <div>

        <label>Markası</label>
        <input type="text" class="form-control" name="marka" required="" placeholder="Markayı Yazın" />

    </div>



    <div>

        <label>Kategori Seçiniz</label>
        @Html.DropDownListFor(m => m.tblkotegoriler.kategoriid, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })  <!-- bu linq sorgusu urunlercontroler da yazdığımız kod ta etkili yöntemi öğren  -->
        <!-- DropDownListFor ile verileri veritabanından çektik yukarda üc kısım var birincisi linq yüntemi ile kategori adı çekecez ,ikincisi listeleme yöntemi ile viewbag.dgr den liste yi seçecek 
            -->
    </div>

    <div>

        <label>Fiyatı</label>
        <input type="text" class="form-control" name="fiyat" required="" placeholder="Fiyatı Yazın" />

    </div>


    <div>

        <label>Stok Adet </label>
        <input type="text" class="form-control" name="stok" required="" placeholder="Stok Adetini Yazın" />

    </div>

   <div style="margin-top:15px" >
       <button class="btn btn-info" >Ürün Ekle </button>
   </div>

</form>

MvcUunStokProjesi/MvcUunStokProjesi/Views/urunler/urungetir.cshtml
@model MvcUunStokProjesi.Models.Entity.tblurunler
@{
    ViewBag.Title = "urungetir";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}


@using (Html.BeginForm("guncelle", "urunler", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.urunid)
    @Html.TextBoxFor(m => m.urunid, new { @class = "form-control" })

    <br />
    @Html.LabelFor(m => m.urunad)
    @Html.TextBoxFor(m => m.urunad, new { @class = "form-control" })

    <br />
    @Html.LabelFor(m => m.marka)
    @Html.TextBoxFor(m => m.marka, new { @class = "form-control" })


   
    @*
        @Html.LabelFor(m => m.urunkategori)
        @Html.DropDownListFor(m => m.tblkotegoriler.kategoriad, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    *@

    @*@Html.TextBoxFor(m => m.urunkategori, new { @class = "form-control" });*@

    <br />
    @Html.LabelFor(m => m.fiyat)
    @Html.TextBoxFor(m => m.fiyat, new { @class = "form-control" })

    <br />
    @Html.LabelFor(m => m.stok)
    @Html.TextBoxFor(m => m.stok, new { @class = "form-control" })

    <br />
    <div>
        <button class="btn btn-warning">Ürün Güncelle </button>
    </div>
</div>
}