MvcUunStokProjesi/MvcUunStokProjesi/Controllers/musteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcUunStokProjesi.Models.Entity;

namespace MvcUunStokProjesi.Controllers
{
    public class musteriController : Controller
    {
        MvcUrunstokEntities2 db = new MvcUrunstokEntities2();
        // GET: musteri
        public ActionResult Index(string p)
        {
            var degerler = from d in db.tblmusteriler select d;// linq sorgusu :musterilerden cek d ye at ve ve d den çek 
            if (!string.IsNullOrEmpty(p))// p değeri boş değilse veya null değilse bunları yap 
            {
                degerler = degerler.Where(m => m.musteriad.Contains(p));// musteri adında değerler p ile aynı olanları getirecek
            }
            return View(degerler.ToList());// paremetre boş sa bunu yap 
            //var degerler = db.tblmusteriler.ToList();
           // return View(degerler);
        }

        [HttpGet]
        public ActionResult yenimusteri()
        {
            return View();
        }


        [HttpPost]
        public ActionResult yenimusteri(tblmusteriler p1)
        {
            if (!ModelState.IsValid) // modelin durumunda doğrulama yapılmadıysa 
            {
                return View("yenimusteri");
            }
            db.tblmusteriler.Add(p1);
            db.SaveChanges();
            return View();
        }

        public ActionResult sil(int id)
        {
            var musteri = db.tblmusteriler.Find(id);
            db.tblmusteriler.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult musterigetir(int id)
        {
            var mus = db.tblmusteriler.Find(id);
            return View("musterigetir", mus); // musterigetir sayfasını geri döndürsün mus verileri ile birlikte 


        }

        public ActionResult guncelle(tblmusteriler p1) 
        {
            var musteri = db.tblmusteriler.Find(p1.musteriid);
            musteri.musteriad = p1.musteriad;
            musteri.musterisoyad = p1.musterisoyad;
            db.SaveChanges();
            return RedirectToAction("Index");//çalıştırırken normal index ten çalıştır ki hatta olmasın  
        }
    }
}

MvcUunStokProjesi/MvcUunStokProjesi/Views/musteri/Index.cshtml
@using MvcUunStokProjesi.Models.Entity
@model List<tblmusteriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Musteri", FormMethod.Get))
            {
<p>
    <b>  Aranacak Müşteri Adı:</b>   @Html.TextBox("p")
    <input type="submit" value="Ara" />
</p>
            }

<table class="table table-bordered" >

    <tr>
        <th> MÜŞTERİ ID </th>
        <th> MÜŞTERİ ADI </th>
        <th> MÜŞTERİ SOYADI </th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Alert </th>
    </tr>
    <tbody>
        @foreach(var mus in Model)
            {
        <tr>
            <th>@mus.musteriid</th>
            <td>@mus.musteriad</td>
            <td>@mus.musterisoyad</td>

            <td> <a href="/musteri/sil/@mus.musteriid " class="btn btn-danger">SİL </a></td>
            <td> <a href="/musteri/musterigetir/@mus.musteriid" class="btn btn-success">GÜNCELLE </a></td>
            <td>@Html.ActionLink("Sil Butonu", "sil", new { id = mus.musteriid }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor musunuz')" })</td>
            <!--return confirm : evet hayır lı uyarı günderir -->
        </tr>
            }
    </tbody>
</table>
<a href="/musteri/yenimusteri/" class="btn btn-primary"> YENİ MÜŞTERİ EKLE</a>

MvcUunStokProjesi/MvcUunStokProjesi/Views/musteri/musterigetir.cshtml
@model MvcUunStokProjesi.Models.Entity.tblmusteriler
@{
    ViewBag.Title = "musterigetir";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}



@using (Html.BeginForm("guncelle", "musteri", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.musteriid)
        @Html.TextBoxFor(m => m.musteriid, new { @class = "form-control" })

        <br />
        @Html.LabelFor(m => m.musteriad)
        @Html.TextBoxFor(m => m.musteriad, new { @class = "form-control" })

        <br />
        @Html.LabelFor(m => m.musterisoyad)
        @Html.TextBoxFor(m => m.musterisoyad, new { @class = "form-control" })
        <br />

        <div>
            <button class="btn btn-warning">Müşteri Güncelle </button>
        </div>
    </div>
}

MvcUunStokProjesi/MvcUunStokProjesi/Views/musteri/yenimusteri.cshtml
@model MvcUunStokProjesi.Models.Entity.tblmusteriler
@{
    ViewBag.Title = "yenimusteri";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<form method="post" class="form-group">

    <div>

        <label>Müşteri Adı</label>
        @Html.TextBoxFor(m => m.musteriad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.musteriad, "", new { Style = "color:red" })

    </div>

    <div>

        <label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="musterisoyad" />

    </div>

    <div style="margin-top:15px" >


       <button class="btn btn-info" id="btn1" >Müşteri Ekle </button> 

    </div>
    <script> 
        $('#btn1').click(function () {
            alert('Müşteri Ekleme işlemi yapıldı...');
        });
    </script>

</form>