MvcUunStokProjesi/MvcUunStokProjesi/Controllers/kategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcUunStokProjesi.Models.Entity;// modelin içindeki entity klasörünü kütüphane olarak tanımladık 
using PagedList;
using PagedList.Mvc;

namespace MvcUunStokProjesi.Controllers
{
    public class kategoriController : Controller
    {
        // GET: kategori
        MvcUrunstokEntities2 db = new MvcUrunstokEntities2();
        public ActionResult Index(int sayfa=1)
        {
            //   var degerler = db.tblkotegoriler.ToList();// select veri tabanı komutları yerine to list kulandık verileri listeleyecek 
            var degerler = db.tblkotegoriler.ToList().ToPagedList(sayfa, 4);// BURDA sayfalamada listelemeyi yapsın 1 ci sayfa 4 öğe döndürsün ,view kısmıda da index te onu da listelemeyi pagelist olarak yap 

            return View(degerler);
        }
        [HttpGet] // buda herhangi bişey yapılmaza yani butona filan basılmazsa sadece sayfayı geriye  döndür 
       public ActionResult yenikategori()
        {
            return View();
        }

        

        [HttpPost]// ben butona bastığım zaman ekleme işlmei yap 
        public ActionResult yenikategori(tblkotegoriler p1) // burda yeni bir sayfa açtık yenikategori aracılığı ile , sadece büyle kullanırsan sıkıntı ekleme her refresh olduğunda yeni ekleme yapar 
            // bu sıkıntı olamamsı için HttpGet ,HttpPost kullanacaz 
        {
            if (!ModelState.IsValid) // modelin durumunda doğrulama yapılmadıysa 
            {
                return View("yenikategori");
            }
            db.tblkotegoriler.Add(p1);
            db.SaveChanges();
            return View();

        }

        public ActionResult sil(int id) // burdaki sil view deki adres te sil nasıl yazılmışsa bunu öyle yaz
        {
            var kategori = db.tblkotegoriler.Find(id);
            db.tblkotegoriler.Remove(kategori);
            db.SaveChanges();// değişliklikleri kaydet 
            return RedirectToAction("Index");
        }

        public ActionResult kategorigetir(int id)
        {
            var ktgr = db.tblkotegoriler.Find(id);
            return View("kategorigetir",ktgr);// kategorigetir view ile birlikte ktgr değerlerinide bize dündürsün 
        }

        public ActionResult guncelle(tblkotegoriler p1)
        {
            var ktg = db.tblkotegoriler.Find(p1.kategoriid);// p1 referansından  den id yi bul
            ktg.kategoriad = p1.kategoriad; // p1 referansından kategoriadı ktg kategoriad a ata 
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcUunStokProjesi/MvcUunStokProjesi/Views/kategori/index.cshtml
@using MvcUunStokProjesi.Models.Entity;
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<tblkotegoriler> 
    <!-- bu yukarda model oluşturduk index sayfasinda tblkategorileri listeleyeck model oluştursun diye  -->
@{
    ViewBag.Title = "index";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<table class="table  table-bordered" >   <!--class="table table-bordered "  BU BOOTSTRAP TAN ÖZELİĞİ -->


    <tr>
        <th>
            KATEGORİ ID
        </th>
        <th>
            KATEGORİ ADI
        </th>
        <th>
            SİL
        </th>
        <th>
            GÜNCELLE
        </th>

    </tr>
    <tbody>
        <!--bu ana grupdaki öğeleri gruplamak için kulanılır -->

        @foreach (var ktgr in Model)
        {

            <!-- döngü veya değişken vb tanımlamak için   et  işareti kulanılır ,model de yukardaki model den geldi -->
        <tr>
            <!--satır oluşur -->
            <th>
                <!--sutun oluşur -->
                @ktgr.kategoriid
            </th>
            <td>
                @ktgr.kategoriad
            </td>
            <td > <a href="/kategori/sil/@ktgr.kategoriid " class="btn btn-danger" >Sil </a></td> 
            <td> <a href="/kategori/kategorigetir/@ktgr.kategoriid" class="btn btn-success">GÜNCELLE </a></td> <!--bu adresler controler deki adresler -->
        </tr>
        }

    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model,sayfa=>Url.Action("Index",new { sayfa}))

<a href="/kategori/yenikategori/" class="btn btn-primary" > YENİ KATEGORİ EKLE</a>

MvcUunStokProjesi/MvcUunStokProjesi/Views/kategori/kategorigetir.cshtml
@model MvcUunStokProjesi.Models.Entity.tblkotegoriler
<!-- yukarda hangi tablo ile işlem yapacaksan yukarda model olarak tanımla -->
@{
    ViewBag.Title = "kategorigetir";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}



@using (Html.BeginForm("guncelle", "kategori", FormMethod.Post))// guncelle gidecek sonra kategoriye sonra post olayı olacak

{
    <div class="form-group">
        @Html.LabelFor(m => m.kategoriid)
        @Html.TextBoxFor(m => m.kategoriid, new { @class = "form-control" })

        <br />

        @Html.LabelFor(m => m.kategoriad)
        @Html.TextBoxFor(m => m.kategoriad, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Kategori Güncelle</button>
    </div>
}

MvcUunStokProjesi/MvcUunStokProjesi/Views/kategori/yenikategori.cshtml
@model MvcUunStokProjesi.Models.Entity.tblkotegoriler
@{
    ViewBag.Title = "yenikategori";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}


<form class="form-group" method="post"> <!-- butona basmak post işlemi sayılır bu yüzden post bunu yap kesin yani -->
   @* <div>
        <label>Kategori Adı </label>
    <input type="text" class="form-control" name="kategoriad"/> <!--name kısmı veritabanı ismi ile aynı olması lazım -->
    </div>
   *@

    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(m=>m.kategoriad ,new {@class="form-control"})
        @Html.ValidationMessageFor(m=>m.kategoriad,"",new {Style="color:red"}) <!-- bunun controler kısmında ki kısmı daki kodları da yazman lazım -->

    </div>
    
    <div style="margin-top:15px">

        <button class="btn btn-info"> Kategori Ekle  </button>

    </div>
</form>